application: vocabeza
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /html
  static_dir: html

- url: /favicon\.ico
  static_files: html/images/favicon.ico
  upload: html/images/favicon\.ico

- url: /.*
  script: servers.app 
  
  
  
libraries:
- name: jinja2
  version: "2.6"  
  

