application: vocabeza
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /.*
  script: servers.app 
  
libraries:
- name: jinja2
  version: "2.6"  
